version: '3.8'

services:
  telegram-calendar-sync:
    build: .
    container_name: telegram-calendar-sync
    restart: unless-stopped
    environment:
      # Telegram API credentials (required)
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_PHONE_NUMBER=${TELEGRAM_PHONE_NUMBER}
      - TELEGRAM_CODE=${TELEGRAM_CODE:-}  # Optional: for two-step verification
      - TELEGRAM_2FA_PASSWORD=${TELEGRAM_2FA_PASSWORD:-}  # Optional: for two-step verification
      
      # Telegram groups to monitor (comma-separated)
      - TELEGRAM_GROUPS=${TELEGRAM_GROUPS}
      
      # LLM API keys (at least one required)
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - GROQ_API_KEY=${GROQ_API_KEY:-}

      # Optional configuration
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - SCAN_LIMIT=${SCAN_LIMIT:-100}
      - CALENDAR_OUTPUT_PATH=/app/data/events.json
      - PROCESSED_MESSAGES_PATH=/app/data/processed_messages.json
      - SESSION_PATH=/app/data/telegram_session
      
    volumes:
      # Persistent data storage
      - ./data:/app/data
      
    # Optional: expose health check endpoint
    # ports:
    #   - "8080:8080"
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

# Optional: Add a web interface for viewing events
  web-interface:
    image: nginx:alpine
    container_name: calendar-web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data:/app/data:ro
    depends_on:
      - telegram-calendar-sync

volumes:
  telegram_data:
    driver: local