name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/ai-telegram-calendar
          git pull origin main
          export DOMAIN_NAME=${{ secrets.DOMAIN_NAME }}
          export CERTBOT_EMAIL=${{ secrets.CERTBOT_EMAIL }}
          docker compose -f docker-compose.yaml up -d --build
